echo "env = {"
echo "  NAMESPACE: '$NAMESPACE',"
echo "  POD_UID: '$POD_UID'"
echo "  POD_NAME: '$POD_NAME',"
echo "  POD_IP: '$POD_IP'"
echo "  USER: '$USER',"
echo "  HOST_IP: '$HOST_IP'"
echo "  KUBEENVIROMENT: '$KUBEENVIROMENT'"
echo "}"
